### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by sukhdevr898** [SreejanPersonal/openai-unofficial#1]
ERROR:openai_unofficial.main:API request failed: 500 Server Error: Internal Server Error for url: https://devsdocode-openai.hf.space/chat/completions
Traceback (most recent call last):                                                                     File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/ai.py", line 7, in <module>
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/openai_unofficial/main.py", line 256, in create
    response = self.api_handler._make_request(                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/openai_unofficial/main.py", line 65, in _make_request
    getattr(e.response, 'json', lambda: None)())                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)                                               requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mian312** [comment]
Basically it is not working simple
